trigger:
- main

jobs:
- job: ubuntu_R_release
  displayName: "Linux, R-release"
  pool:
    vmImage: "Ubuntu-22.04"
  steps:
  - template: azure-pipelines/ubuntu-install-R.yml
  - template: azure-pipelines/customize-R-startup.yml
  - template: azure-pipelines/R-sessioninfo.yml
  - template: azure-pipelines/ubuntu-install-dependencies.yml
  - template: azure-pipelines/build-package.yml
  - template: azure-pipelines/check-package.yml
  - template: azure-pipelines/code-coverage.yml
  - template: azure-pipelines/static-code-analysis.yml
  - task: DotNetCoreInstaller@0
    inputs:
      packageType: sdk
      version: 2.2.207
      installationPath: $(Agent.ToolsDirectory)/dotnet
    displayName: "Install dotnet core"
  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: 'Cobertura'
      summaryFileLocation: 'coverage.xml'
