# Run static code analysis
steps:
- bash: |
    Rscript \
      -e "install.packages('lintr')" \
      -e "library(lintr)" \
      -e "l <- lint_package()" \
      -e "print(l)" \
      -e "quit(save = 'no', status = length(l) > 0)"
  displayName: 'Static analysis of R code'
